quarkus.http.host=0.0.0.0
quarkus.package.jar.type=uber-jar

# JNation 2026 API
quarkus.rest-client."pt.jnation.tv.sessionize.SessionizeClient".url=https://sessionize.com/api/v2/y7xmw2us/view/

# Rooms / Sessions
jnation.tv.rooms[0].name=Grand Auditorium
jnation.tv.rooms[0].color=red
jnation.tv.rooms[0].css-color=#e74c3c
jnation.tv.rooms[0].stream=https://www.youtube.com/embed/xMNu5GzUU1o?controls=1&autoplay=1&mute=0
jnation.tv.rooms[1].name=Old Church
jnation.tv.rooms[1].color=blue
jnation.tv.rooms[1].css-color=#3498db
jnation.tv.rooms[2].name=Mondego
jnation.tv.rooms[2].color=green
jnation.tv.rooms[2].css-color=#27ae60
jnation.tv.rooms[3].name=Almedina
jnation.tv.rooms[3].color=orange
jnation.tv.rooms[3].css-color=#e67e22
jnation.tv.rooms[4].name=Sofia
jnation.tv.rooms[4].color=purple
jnation.tv.rooms[4].css-color=#8e44ad
jnation.tv.rooms[5].name=Conventual
jnation.tv.rooms[5].color=grey
jnation.tv.rooms[5].css-color=#34495E
jnation.tv.rooms[6].name=Aeminium
jnation.tv.rooms[6].color=yellow
jnation.tv.rooms[6].css-color=#f1c40f

# General Media
# YouTube with autoplay and sound only work if users previously unmuted the video (so we may need to do this in every TV)
jnation.tv.media.default[0]=https://display.socialwalls.com/167096
jnation.tv.media.default[1]=sessions/2026-05-26
jnation.tv.media.default[2]=mobile-app.jpg
jnation.tv.media.keynote[3]=jnation2026-kids.png
jnation.tv.media.keynote[4]=jnation2026-stats.png
jnation.tv.media.default[5]=jnation2026-sponsors-platinum.jpg
jnation.tv.media.default[6]=jnation2026-sponsors-gold.jpg
jnation.tv.media.default[7]=jnation2026-sponsors-others.jpg
#jnation.tv.media.default[6]=heinz-course.png

jnation.tv.media.keynote[0]=mobile-app.jpg
jnation.tv.media.keynote[1]=jnation2026-kids.png
jnation.tv.media.keynote[2]=jnation2026-stats.png
jnation.tv.media.keynote[3]=jnation2026-gamification.jpg
jnation.tv.media.keynote[4]=jnation2026-sponsors-platinum.jpg
jnation.tv.media.keynote[5]=jnation2026-sponsors-gold.jpg
jnation.tv.media.keynote[6]=jnation2026-sponsors-others.jpg
jnation.tv.media.keynote[7]=jnation2026-venue-map.jpg
